language: node_js
node_js:
  - "8"
  - "8.7"
  - "8.6"
  - "8.5"
  - "8.4"
  - "8.3"
  - "8.2"
  - "8.1"
  - "8.0"
  - "7"
  - "7.6" # Minimum
script:
  - npm test
  - npm run check-coverage
  - npm run lint
